### ISSUE TITLE
Add support for DynamoDbFlatten

### ISSUE THREAD

**Issue by vladas** [oharaandrew314/dynamodb-kotlin-module#5]

**Comment by oharaandrew314** [comment]
This isn't something I have any desire to add myself.  Feel free to submit a PR if it's important for you.

**Comment by benkeil** [comment]
Would be also interested intros feature.

**Comment by oharaandrew314** [comment]
This is now supported in version 0.6 via 891135661203c4a9f9708c34291818f2efdf4496
