### ISSUE TITLE
Doesn't support properties defined in class body

### ISSUE THREAD

**Issue by skibak** [oharaandrew314/dynamodb-kotlin-module#7]
I have data class with somer properties defined in constructor and some in class body, e.g.

```
data class MyClass(
    @DynamoKtAttribute
    var prop1: String? = null
) {
    @DynamoKtAttribute
    var prop2: String = "def"  
}
```

When schema for it created, code here https://github.com/oharaandrew314/dynamodb-kotlin-module/blob/master/src/main/kotlin/io/andrewohara/dynamokt/DataClassAttribute.kt#L55
builds incorrect association between attributes and constructor parameter.

So later mapToItem fails to create instance because of constructor arguments mismatch.

**Comment by oharaandrew314** [comment]
The class you've provided is just a java bean; you should be able to use the `BeanTableSchema`; see [this guide](https://betterprogramming.pub/aws-java-sdk-v2-dynamodb-enhanced-client-with-kotlin-spring-boot-application-f880c74193a2) for using beans with the v2 sdk.

This module is intended for use with idiomatic Kotlin data classes like
```kotlin
data class Record(
  @DynamoKtPartitionKey val id: UUID,
  val name: String
)
```

**Comment by skibak** [comment]
Yes, it is now.
I just tried to migrate from using standard annotation to more Kotlin friendly.
Minimum we should detect this situation and throw error.
Ideally we should invoke constructor, and then invoke remaining property setters.

To explain context:
I'm trying to come with better way to support calculated fields.
I wanted to put required fields in constructor, and define calculated fields (composite keys used for indexing) inside, plus override some properties setters to trigger fields calculation.

**Comment by oharaandrew314** [comment]
Yeah, you're right.  I'll look into an improvement.

**Comment by oharaandrew314** [comment]
I've added a check to version 0.2.2
