### ISSUE TITLE
CreateTableTest fails with newer dynamodb-enhanced:2.20.+ version

### ISSUE THREAD

**Issue by padenn2** [oharaandrew314/dynamodb-kotlin-module#8]
The "original createTable will lose indices" unit test will fail if `dynamodb-enhanced` is upgraded to a newer 2.20.+ version. 

```
> Task :test

CreateTableTest > original createTable will lose indices() FAILED
    java.lang.AssertionError at CreateTableTest.kt:31

57 tests completed, 1 failed
```

**Comment by padenn2** [comment]
It appears https://github.com/aws/aws-sdk-java-v2/releases/tag/2.20.86 is the exact upstream version that causes the test to break. With 2.20.85 the test passes.

**Comment by cjkent** [comment]
Presumably [this commit](https://github.com/aws/aws-sdk-java-v2/commit/ef2aa905c87bbc8088bc8ab4a11a85580a1d8209) is the issue? It fixes the bug that `DynamoDbTable.createTableWithIndices()` works around.

**Comment by oharaandrew314** [comment]
Wow, it looks like the SDK maintainers changed their mind about creating the indices by default.  I'll look into a compatibility fix and document that `createTableWithIndices` is only necessary prior to `2.20.86`

**Comment by oharaandrew314** [comment]
I've upgraded the minimum SDK version to `2.20.86`, updated the tests, and deprecated `createTableWithIndices`.  Upgrading to the new 0.2.3 release shouldn't be necessary (since this issue only affects building), but it's available as an option regardless.

**Comment by padenn2** [comment]
Thx for the quick fix @oharaandrew314 !
